mystmt_lexer.go: /tmp/antlr-4.7.2-complete.jar MyStmt.g4
	java -jar /tmp/antlr-4.7.2-complete.jar -Dlanguage=Go -package mystmt MyStmt.g4

/tmp/antlr-4.7.2-complete.jar:
	wget -O $@ https://www.antlr.org/download/antlr-4.7.2-complete.jar
